name = "currency-exchange-notifier-cf"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

[triggers]
crons = ["0 8,10,19 * * mon-fri"]